[package]
name = "rofi-bw-common"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
bincode = "2.0.0-rc.1"
rand = "0.8.5"
subtle = "2.4.1"
zeroize = { version = "1.5.6", features = ["std"] }
