{
  name: "Release",
  on: { "release": { types: ["published"] } },
  jobs: {
    "release": {
      name: "Release",
      strategy: {
        fail-fast: true,
        matrix: {
          "target": ["x86_64-unknown-linux-gnu"],
        },
      },
      runs-on: "ubuntu-latest",
      env: {
        "archive_name": "rofi-bw-${{ github.ref_name }}-${{ matrix.target }}.tar.gz",
      },
      steps: [
        # We need to build ICU from source because Ubuntu doesn’t compile it with -fPIC
        {
          name: "Checkout ICU",
          uses: "actions/checkout@v3",
          with: {
            repository: "unicode-org/icu",
            path: "icu",
          },
        },
        {
          name: "Configure ICU",
          env: {
            "CFLAGS": "-fPIC",
            "configure_args": "--with-data-packaging=archive --enable-static --disable-shared --disable-tests",
          },
          run: "mkdir icu-build && cd icu-build && ../icu/icu4c/source/runConfigureICU Linux ${{ env.configure_args }}",
        },
        {
          name: "Build ICU",
          run: "cd icu-build && make && sudo make install",
        },
        {
          name: "Checkout",
          uses: "actions/checkout@v3",
        },
        {
          name: "Install Rust",
          uses: "actions-rs/toolchain@v1",
          with: {
            toolchain: "stable",
            profile: "minimal",
            target: "${{ matrix.target }}",
          },
        },
        {
          name: "Install packages",
          run: "sudo apt install libcairo2-dev libdbus-1-dev libpango1.0-dev llvm",
        },
        {
          name: "Build",
          # Statically link against ICU because it has frequently changing version numbers
          run: "cargo dev build --release",
        },
        {
          name: "Make archive",
          run: "tar cvzf ${{ env.archive_name }} build install.sh",
        },
        {
          name: "Upload release archive",
          uses: "softprops/action-gh-release@v1",
          with: { files: "${{ env.archive_name }}" },
        },
      ],
    },
  },
}
